import 'package:portefeuille/core/data/models/transaction.dart';
import 'package:portefeuille/core/data/models/transaction_type.dart';
import 'package:portefeuille/core/data/models/asset_type.dart';
import 'package:uuid/uuid.dart';

List<Transaction> getDemoTransactions(
  Uuid uuid,
  String peaAccountId,
  String ctoAccountId,
  String assuranceVieAccountId,
  String cryptoAccountId,
) {
  return [
    // ===== 2020 : OUVERTURE DES COMPTES =====
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2020, 1, 15),
      amount: 5000.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Buy,
      date: DateTime(2020, 1, 20),
      assetTicker: 'CW8.PA',
      assetName: 'Amundi MSCI World UCITS ETF',
      assetType: AssetType.ETF,
      quantity: 15,
      price: 300.0,
      fees: 7.50,
      amount: -4500.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: ctoAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2020, 3, 1),
      amount: 3000.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: ctoAccountId,
      type: TransactionType.Buy,
      date: DateTime(2020, 3, 10),
      assetTicker: 'AAPL',
      assetName: 'Apple Inc.',
      assetType: AssetType.Stock,
      quantity: 20,
      price: 120.0,
      fees: 9.90,
      amount: -2400.0,
    ),

    // ===== 2021 : RENFORCEMENT RÉGULIER =====
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2021, 1, 5),
      amount: 500.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Buy,
      date: DateTime(2021, 1, 10),
      assetTicker: 'MC.PA',
      assetName: 'LVMH Moët Hennessy Louis Vuitton',
      assetType: AssetType.Stock,
      quantity: 1,
      price: 480.0,
      fees: 5.0,
      amount: -480.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: ctoAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2021, 6, 15),
      amount: 2000.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: ctoAccountId,
      type: TransactionType.Buy,
      date: DateTime(2021, 6, 20),
      assetTicker: 'MSFT',
      assetName: 'Microsoft Corporation',
      assetType: AssetType.Stock,
      quantity: 5,
      price: 280.0,
      fees: 9.90,
      amount: -1400.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: cryptoAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2021, 11, 1),
      amount: 1500.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: cryptoAccountId,
      type: TransactionType.Buy,
      date: DateTime(2021, 11, 5),
      assetTicker: 'BTC-EUR',
      assetName: 'Bitcoin',
      assetType: AssetType.Crypto,
      quantity: 0.03,
      price: 50000.0,
      fees: 7.50,
      amount: -1500.0,
    ),

    // ===== 2022 : DIVERSIFICATION =====
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2022, 3, 1),
      amount: 2000.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Buy,
      date: DateTime(2022, 3, 5),
      assetTicker: 'CW8.PA',
      assetName: 'Amundi MSCI World UCITS ETF',
      assetType: AssetType.ETF,
      quantity: 5,
      price: 380.0,
      fees: 5.0,
      amount: -1900.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Buy,
      date: DateTime(2022, 5, 10),
      assetTicker: 'TTE.PA',
      assetName: 'TotalEnergies SE',
      assetType: AssetType.Stock,
      quantity: 15,
      price: 48.0,
      fees: 5.0,
      amount: -720.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: assuranceVieAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2022, 9, 1),
      amount: 10000.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: assuranceVieAccountId,
      type: TransactionType.Buy,
      date: DateTime(2022, 9, 5),
      assetTicker: 'FONDS-EUROS',
      assetName: 'Fonds en Euros Suravenir',
      assetType: AssetType.Other,
      quantity: 10000,
      price: 1.0,
      fees: 0.0,
      amount: -10000.0,
    ),

    // ===== 2023 : PREMIERS DIVIDENDES =====
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Dividend,
      date: DateTime(2023, 4, 15),
      assetTicker: 'MC.PA',
      assetName: 'Dividende LVMH',
      amount: 12.0,
      fees: 0.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Dividend,
      date: DateTime(2023, 6, 20),
      assetTicker: 'TTE.PA',
      assetName: 'Dividende TotalEnergies',
      amount: 9.75,
      fees: 0.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: assuranceVieAccountId,
      type: TransactionType.Interest,
      date: DateTime(2023, 12, 31),
      assetTicker: 'FONDS-EUROS',
      assetName: 'Intérêts Fonds Euros 2023',
      amount: 250.0,
      fees: 0.0,
    ),

    // ===== 2024 : PRISE DE PROFIT =====
    Transaction(
      id: uuid.v4(),
      accountId: ctoAccountId,
      type: TransactionType.Sell,
      date: DateTime(2024, 2, 10),
      assetTicker: 'AAPL',
      assetName: 'Apple Inc.',
      assetType: AssetType.Stock,
      quantity: 10,
      price: 185.0,
      fees: 9.90,
      amount: 1850.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: cryptoAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2024, 5, 1),
      amount: 1000.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: cryptoAccountId,
      type: TransactionType.Buy,
      date: DateTime(2024, 5, 5),
      assetTicker: 'ETH-EUR',
      assetName: 'Ethereum',
      assetType: AssetType.Crypto,
      quantity: 0.5,
      price: 2000.0,
      fees: 5.0,
      amount: -1000.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Dividend,
      date: DateTime(2024, 4, 15),
      assetTicker: 'MC.PA',
      assetName: 'Dividende LVMH',
      amount: 13.0,
      fees: 0.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Dividend,
      date: DateTime(2024, 6, 20),
      assetTicker: 'TTE.PA',
      assetName: 'Dividende TotalEnergies',
      amount: 10.50,
      fees: 0.0,
    ),

    // ===== 2025 : RENFORCEMENT RÉCENT =====
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Deposit,
      date: DateTime(2025, 1, 10),
      amount: 1000.0,
    ),
    Transaction(
      id: uuid.v4(),
      accountId: peaAccountId,
      type: TransactionType.Buy,
      date: DateTime(2025, 1, 15),
      assetTicker: 'CW8.PA',
      assetName: 'Amundi MSCI World UCITS ETF',
      assetType: AssetType.ETF,
      quantity: 2,
      price: 450.0,
      fees: 2.50,
      amount: -900.0,
    ),
  ];
}
